### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by SRDdev** [SRDdev/Calculatorapp#1]
Traceback (most recent call last):
  File "C:\Users\lenovo\PycharmProjects\pythonProject\Calculator.py", line 47, in <module>
    button_equal=Button(root,text="=",padx=30,pady=30,command=equals()).grid(row=5,column=1)
  File "C:\Users\lenovo\PycharmProjects\pythonProject\Calculator.py", line 24, in equals
    list_of_numbers.append(int(num1))
ValueError: invalid literal for int() with base 10: ''

Please solve , no permissions required .

**Comment by SRDdev** [comment]
Thank you @
